{% set version = "2.3.7" %}

package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a8c0582fa72e48272efbd4b92bf51f60e7affbf011083ca559aa1e941191612e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps .


requirements:
  host:
    - python >=3.10,<3.13
    - pip
  run:
    - python >=3.10,<3.13
    - pip
    - geopandas <1
    - glpk
    - openpyxl <4
    - matplotlib <4
    - xlrd <3
    - pyomo <7
    - numpy <2
    - pandas <3
    - scipy <2
    - scikit-learn >=1.2,<2
    - xarray <=2024.3
    - rasterio <2
    - netcdf4 <2
    - tsam
    - pwlf <3
    - psutil <6
    - gurobi-logtools <4

test:
  imports:
    - fine
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
    - k-knosala
