{% set version = "2.4.0" %}

package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: df17ef91d5f2fb35f5fc110e5d96566b3be57518ba7d3152cbad395df7372621

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools >=61.0.0
  run:
    - python >=3.10,<3.13
    - pip
    - geopandas <1
    - glpk
    - openpyxl <4
    - matplotlib <4
    - xlrd <3
    - pyomo <=6.7.3
    - numpy <2
    - pandas <3
    - scipy <2
    - scikit-learn >=1.2,<2
    - xarray <=2024.3
    - rasterio <2
    - netcdf4 <2
    - tsam
    - pwlf <3
    - psutil <6
    - gurobi-logtools <4

test:
  imports:
    - fine
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
    - k-knosala
