{% set python_min = "3.10" %}
{% set version = "2.4.0" %}


package:
  name: fine
  version: {{ version }}

source:
  url: https://github.com/FZJ-IEK3-VSA/FINE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: df17ef91d5f2fb35f5fc110e5d96566b3be57518ba7d3152cbad395df7372621

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation


requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0.0
  run:
    - python >={{ python_min }},<3.13
    - pip
    - geopandas <=0.14.4
    - glpk
    - openpyxl <3.1.5
    - matplotlib <3.9.2
    - xlrd <2.0.1
    - pyomo <=6.8.0
    - numpy <1.26.4
    - pandas >=2,<=2.2.3
    - scipy <=1.14.1
    - scikit-learn >=1.2,<=1.5.2
    - xarray <=2024.3
    - rasterio <=1.4.1
    - netcdf4 <=1.7.2
    - tsam
    - pwlf <=2.2.1
    - psutil <=5.9.8
    - gurobi-logtools <=3.1.0
    - ipykernel <=6.29.5

test:
  imports:
    - fine
    - pandas
    - numpy
  source_files:
    - .
  requires:
    - {{ python_min }}
    - pytest
  commands:
    - pytest test/

about:
  home: https://github.com/FZJ-IEK3-VSA/FINE.git
  summary: The FINE python package provides a framework for modeling, optimizing and assessing energy systems.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - noah80
    - t-gross
    - julian-belina
